kind: Service
apiVersion: v1
metadata:
  name: rollout-preprocess-preview
spec:
  type: LoadBalancer
  selector:
    app: rollout-preprocess
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
