apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: fastapi-server
  namespace: argo
  labels:
    app: fastapi

spec:
  entrypoint: fastapi
  volumes:
  - name: test-volume
    hostPath:
      path: /root/argo
#      path: /home/azureuser/scripts
      type: Directory

  templates:

  - name: fastapi
#    daemon: true
    container: 
      image: python:workflow-0.3.5
      command:
      - python
      args: 
      - '/code/fastapitest.py'
      volumeMounts:
      - name: test-volume
        mountPath: /code
      ports:
        - containerPort: 5050
          name: http
      
    nodeSelector:
      kubernetes.io/hostname: trtis-worker-2

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-server-service
spec:
  type: NodePort
  ports:
  - port: 5050
    targetPort: http
    nodePort: 32323
    protocol: TCP
    name: http
  selector:
    app: fastapi
