apiVersion: v1
kind: Service
metadata:
  name: fastapi-server-service
spec:
  type: LoadBalancer
  ports:
  - port: 5050
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: fastapi-server