apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: fastapi-server
  namespace: argo

spec:
  entrypoint: fastapi
  volumes:
  - name: test-volume
    hostPath:
      path: /root/argo
      type: Directory

  templates:
  - name: fastapi
    container: 
      image: python:workflow-0.3.5
      command:
      - python
      source: | 
        import uvicorn
        from fastapi import FastAPI

        app = FastAPI()

        @app.get('/test')
        def test():
          return 'hello'

        uvicorn.run('fastapitest:app', port=5050, host='0.0.0.0')
      
    nodeSelector:
      kubernetes.io/hostname: trtis-worker-2

