apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: script-template
  namespace: argo
spec:
  entrypoint: scripttest
  templates:
    - name: scripttest
      script:
        image: 'python:workflow-0.3.5'
        command:
          - python
        source: |
          import time

          for i in range(1, 100):
            print(i)
            sleep(2)

  nodeSelector:
    kubernetes.io/hostname: trtis-worker-2
