apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: test-workflow
  namespace: argo

spec:
  entrypoint: test-steps
  templates:

  - name: testflow
    daemon: true
    container: 
      image: python:workflow-0.1
      command: ["while true; do", "echo hello", "done"]

  - name: test-steps
    steps:
    - - name: step01
        template: testflow  

    - - name: step02
        template: testflow
