apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: test-workflow
  namespace: argo

spec:
  entrypoint: test-steps
  templates:

  - name: testflow
    volumes:
    - name: test-volume
      hostpath:
        path: /root/argo
        type: Directory
    daemon: true
    container: 
      image: python:workflow-0.1
      command:
      - python
      args: 
      - '/code/helloloop.py'
      volumeMounts:
      - name: test-volume
        mountPath: /code

  - name: test-steps
    steps:
    - - name: step01
        template: testflow  

    - - name: step02
        template: testflow
