apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: test-workflow
  namespace: argo

spec:
  entrypoint: test-steps
  volumes:
  - name: test-volume
    hostPath:
#      path: /root/argo
      path: /home/azureuser/scripts
      type: Directory

  templates:

  - name: testflow
    daemon: true
    container: 
      image: python:workflow-0.1
      command:
      - python
      args: 
      - '/code/helloloop.py'
      volumeMounts:
      - name: test-volume
        mountPath: /code
    nodeSelector:
      kubernetes.io/hostname: trtis-worker-1

  - name: test-steps
    steps:
    - - name: step01
        template: testflow  

    - - name: step02
        template: testflow
