---
apiVersion: v1
kind: Service
metadata:
  name: triton-custom-metrics-api
  namespace: default
spec:
  selector:
    app: triton-custom-metrics-apiserver
  ports:
  - name: https
    port: 443
    targetPort: 6443
---
