---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: triton-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: triton
  minReplicas: 1
  maxReplicas: 7
  metrics:
  - type: Pods
    pods:
      metric:
        name: avg_time_queue_us
      target:
       type: AverageValue
       averageValue: 4000m
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
---
